name: .NET Service preview

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DIRECTORY: src
  CONFIGURATION: Release
  HOST_SOLUTION_NAME: TaskManagement.Service.Auth.Host
  DOCKER_REPOSITORY: taskmanagement-service-auth
  DOCKER_NAMESPACE: wingunt

jobs:
  build:
    name: Build .Net
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ${{ env.DIRECTORY }}
      run: dotnet restore
    - name: Build
      working-directory: ${{ env.DIRECTORY }}
      run: dotnet build --no-restore --configuration ${{ env.CONFIGURATION }}
    - name: Test
      working-directory: ${{ env.DIRECTORY }}
      run: dotnet test --verbosity normal

  docker:
    name: Push Docker image to Docker Hub 
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
    - name: Build docker repo
      working-directory: ${{ env.DIRECTORY }}/${{ env.HOST_SOLUTION_NAME }}
      run: docker build docker -t ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}:latest
    - name: Push to Docker Hub
      run: docker push ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}:latest
