name: .NET Service preview

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ feature/* ]

env:
  DIRECTORY: src
  CONFIGURATION: Debug
  TAG_SOLUTION_NAME: taskmanagement-service-host
  DOCKER_NAMESPACE: wingunt

jobs:
  build:
    name: Build .Net
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ${{ env.DIRECTORY }}
      run: dotnet restore
    - name: Build
      working-directory: ${{ env.DIRECTORY }}
      run: dotnet build --no-restore --configuration ${{ env.CONFIGURATION }}
    - name: Test
      working-directory: ${{ env.DIRECTORY }}
      run: dotnet test --verbosity normal

  docker:
    name: Push Docker image to Docker Hub 
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Build docker repo
      run: docker build TaskManagement.Service.Auth.Host\\docker -t ${{ env.DOCKER_NAMESPACE }}/${{ env.TAG_SOLUTION_NAME }}:latest
    - name: Push to Docker Hub
      run: docker push ${{ env.DOCKER_NAMESPACE }}/${{ env.TAG_SOLUTION_NAME }}
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: wingunt/taskmanagement-service-auth
      
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
